services:
  - name: idea-board
    type: web
    env: node
    plan: free
    branch: main
    buildCommand: 'npm --prefix frontend install && npm --prefix frontend run build'
    startCommand: 'node backend/server.js'
    root: ./